export interface VocabListEntry {
  word: string
  definitionZh: string
  level: "basic" | "intermediate" | "advanced"
  weight: number
}

export const VOCAB_LIST: VocabListEntry[] = [
  { word: "ability", definitionZh: "能力；才能", level: "basic", weight: 1 },
  { word: "accept", definitionZh: "接受；同意", level: "basic", weight: 1 },
  { word: "achieve", definitionZh: "实现；达到", level: "basic", weight: 1 },
  { word: "advice", definitionZh: "建议；忠告", level: "basic", weight: 1 },
  { word: "afford", definitionZh: "买得起；承担得起", level: "basic", weight: 1 },
  { word: "although", definitionZh: "虽然；尽管", level: "basic", weight: 1 },
  { word: "avoid", definitionZh: "避免；避开", level: "basic", weight: 1 },
  { word: "balance", definitionZh: "平衡；余额", level: "basic", weight: 1 },
  { word: "behavior", definitionZh: "行为；举止", level: "basic", weight: 1 },
  { word: "benefit", definitionZh: "好处；受益", level: "basic", weight: 1 },
  { word: "compare", definitionZh: "比较；对照", level: "basic", weight: 1 },
  { word: "consider", definitionZh: "考虑；认为", level: "basic", weight: 1 },
  { word: "contain", definitionZh: "包含；容纳", level: "basic", weight: 1 },
  { word: "create", definitionZh: "创造；创建", level: "basic", weight: 1 },
  { word: "culture", definitionZh: "文化；教养", level: "basic", weight: 1 },
  { word: "describe", definitionZh: "描述；形容", level: "basic", weight: 1 },
  { word: "develop", definitionZh: "发展；开发", level: "basic", weight: 1 },
  { word: "effort", definitionZh: "努力；成就", level: "basic", weight: 1 },
  { word: "environment", definitionZh: "环境；周围状况", level: "basic", weight: 1 },
  { word: "experience", definitionZh: "经验；经历", level: "basic", weight: 1 },
  { word: "factor", definitionZh: "因素；要素", level: "intermediate", weight: 2 },
  { word: "feature", definitionZh: "特征；功能", level: "intermediate", weight: 2 },
  { word: "flexible", definitionZh: "灵活的；可弯曲的", level: "intermediate", weight: 2 },
  { word: "frequent", definitionZh: "频繁的；常见的", level: "intermediate", weight: 2 },
  { word: "generate", definitionZh: "产生；生成", level: "intermediate", weight: 2 },
  { word: "identify", definitionZh: "识别；确认", level: "intermediate", weight: 2 },
  { word: "impact", definitionZh: "影响；冲击", level: "intermediate", weight: 2 },
  { word: "improve", definitionZh: "改善；提高", level: "intermediate", weight: 2 },
  { word: "indicate", definitionZh: "表明；指出", level: "intermediate", weight: 2 },
  { word: "insight", definitionZh: "洞察；见解", level: "intermediate", weight: 2 },
  { word: "maintain", definitionZh: "维持；维护", level: "intermediate", weight: 2 },
  { word: "method", definitionZh: "方法；办法", level: "intermediate", weight: 2 },
  { word: "observe", definitionZh: "观察；遵守", level: "intermediate", weight: 2 },
  { word: "obvious", definitionZh: "明显的；显然的", level: "intermediate", weight: 2 },
  { word: "pattern", definitionZh: "模式；图案", level: "intermediate", weight: 2 },
  { word: "predict", definitionZh: "预测；预言", level: "intermediate", weight: 2 },
  { word: "priority", definitionZh: "优先事项；优先权", level: "intermediate", weight: 2 },
  { word: "require", definitionZh: "需要；要求", level: "intermediate", weight: 2 },
  { word: "resource", definitionZh: "资源；资料", level: "intermediate", weight: 2 },
  { word: "significant", definitionZh: "重要的；显著的", level: "intermediate", weight: 2 },
  { word: "ambiguous", definitionZh: "模棱两可的；含糊的", level: "advanced", weight: 3 },
  { word: "approximate", definitionZh: "近似的；大约", level: "advanced", weight: 3 },
  { word: "coherent", definitionZh: "连贯的；一致的", level: "advanced", weight: 3 },
  { word: "constraint", definitionZh: "限制；约束", level: "advanced", weight: 3 },
  { word: "derive", definitionZh: "获得；源自", level: "advanced", weight: 3 },
  { word: "eliminate", definitionZh: "消除；排除", level: "advanced", weight: 3 },
  { word: "explicit", definitionZh: "明确的；直率的", level: "advanced", weight: 3 },
  { word: "feasible", definitionZh: "可行的；行得通的", level: "advanced", weight: 3 },
  { word: "integrate", definitionZh: "整合；融入", level: "advanced", weight: 3 },
  { word: "interpret", definitionZh: "解释；理解", level: "advanced", weight: 3 },
  { word: "leverage", definitionZh: "利用；杠杆作用", level: "advanced", weight: 3 },
  { word: "migrate", definitionZh: "迁移；移居", level: "advanced", weight: 3 },
  { word: "optimize", definitionZh: "优化；使最佳", level: "advanced", weight: 3 },
  { word: "persist", definitionZh: "持续；坚持", level: "advanced", weight: 3 },
  { word: "pragmatic", definitionZh: "务实的；实际的", level: "advanced", weight: 3 },
  { word: "refine", definitionZh: "改进；提炼", level: "advanced", weight: 3 },
  { word: "resolve", definitionZh: "解决；决定", level: "advanced", weight: 3 },
  { word: "scope", definitionZh: "范围；作用域", level: "advanced", weight: 3 },
  { word: "validate", definitionZh: "验证；确认有效", level: "advanced", weight: 3 },
  { word: "workflow", definitionZh: "工作流程", level: "advanced", weight: 3 },
]
